version: "3"

services:
  web:
    build: ./web
    ports:
      - "${PORT_WEB_HOST}:80"

  relay:
    build: ./relay
    ports:
      - "${PORT_RELAY_STREAM_HOST}:8081"
      - "${PORT_RELAY_WS_HOST}:8082"
