version: "3"

services:
  web:
    build: ./web
    ports:
      - "903:80" # port web server

  relay:
    build: ./relay
    ports:
      - "901:8081" # port for video stream to relay
      - "902:8082" # port for websocket connections
